// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryRepository is an autogenerated mock type for the DeliveryRepository type
type DeliveryRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *DeliveryRepository) Find(id string) (hammer.Delivery, error) {
	ret := _m.Called(id)

	var r0 hammer.Delivery
	if rf, ok := ret.Get(0).(func(string) hammer.Delivery); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(hammer.Delivery)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: limit, offset
func (_m *DeliveryRepository) FindAll(limit int, offset int) ([]hammer.Delivery, error) {
	ret := _m.Called(limit, offset)

	var r0 []hammer.Delivery
	if rf, ok := ret.Get(0).(func(int, int) []hammer.Delivery); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindToDispatch provides a mock function with given fields: limit, offset
func (_m *DeliveryRepository) FindToDispatch(limit int, offset int) ([]hammer.Delivery, error) {
	ret := _m.Called(limit, offset)

	var r0 []hammer.Delivery
	if rf, ok := ret.Get(0).(func(int, int) []hammer.Delivery); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: tx, delivery
func (_m *DeliveryRepository) Store(tx hammer.TxRepository, delivery *hammer.Delivery) error {
	ret := _m.Called(tx, delivery)

	var r0 error
	if rf, ok := ret.Get(0).(func(hammer.TxRepository, *hammer.Delivery) error); ok {
		r0 = rf(tx, delivery)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
