// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// DeliveryAttemptRepository is an autogenerated mock type for the DeliveryAttemptRepository type
type DeliveryAttemptRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *DeliveryAttemptRepository) Find(id string) (hammer.DeliveryAttempt, error) {
	ret := _m.Called(id)

	var r0 hammer.DeliveryAttempt
	if rf, ok := ret.Get(0).(func(string) hammer.DeliveryAttempt); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(hammer.DeliveryAttempt)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: findOptions
func (_m *DeliveryAttemptRepository) FindAll(findOptions hammer.FindOptions) ([]hammer.DeliveryAttempt, error) {
	ret := _m.Called(findOptions)

	var r0 []hammer.DeliveryAttempt
	if rf, ok := ret.Get(0).(func(hammer.FindOptions) []hammer.DeliveryAttempt); ok {
		r0 = rf(findOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.DeliveryAttempt)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hammer.FindOptions) error); ok {
		r1 = rf(findOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: tx, deliveryAttempt
func (_m *DeliveryAttemptRepository) Store(tx hammer.TxRepository, deliveryAttempt *hammer.DeliveryAttempt) error {
	ret := _m.Called(tx, deliveryAttempt)

	var r0 error
	if rf, ok := ret.Get(0).(func(hammer.TxRepository, *hammer.DeliveryAttempt) error); ok {
		r0 = rf(tx, deliveryAttempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
