// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// MessageService is an autogenerated mock type for the MessageService type
type MessageService struct {
	mock.Mock
}

// Create provides a mock function with given fields: message
func (_m *MessageService) Create(message *hammer.Message) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(*hammer.Message) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MessageService) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *MessageService) Find(id string) (hammer.Message, error) {
	ret := _m.Called(id)

	var r0 hammer.Message
	if rf, ok := ret.Get(0).(func(string) hammer.Message); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(hammer.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: findOptions
func (_m *MessageService) FindAll(findOptions hammer.FindOptions) ([]hammer.Message, error) {
	ret := _m.Called(findOptions)

	var r0 []hammer.Message
	if rf, ok := ret.Get(0).(func(hammer.FindOptions) []hammer.Message); ok {
		r0 = rf(findOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hammer.FindOptions) error); ok {
		r1 = rf(findOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
