// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MigrationRepository is an autogenerated mock type for the MigrationRepository type
type MigrationRepository struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *MigrationRepository) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
