// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type SubscriptionRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: tx, id
func (_m *SubscriptionRepository) Delete(tx hammer.TxRepository, id string) error {
	ret := _m.Called(tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(hammer.TxRepository, string) error); ok {
		r0 = rf(tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: id
func (_m *SubscriptionRepository) Find(id string) (hammer.Subscription, error) {
	ret := _m.Called(id)

	var r0 hammer.Subscription
	if rf, ok := ret.Get(0).(func(string) hammer.Subscription); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(hammer.Subscription)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: findOptions
func (_m *SubscriptionRepository) FindAll(findOptions hammer.FindOptions) ([]hammer.Subscription, error) {
	ret := _m.Called(findOptions)

	var r0 []hammer.Subscription
	if rf, ok := ret.Get(0).(func(hammer.FindOptions) []hammer.Subscription); ok {
		r0 = rf(findOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(hammer.FindOptions) error); ok {
		r1 = rf(findOptions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: tx, subscription
func (_m *SubscriptionRepository) Store(tx hammer.TxRepository, subscription *hammer.Subscription) error {
	ret := _m.Called(tx, subscription)

	var r0 error
	if rf, ok := ret.Get(0).(func(hammer.TxRepository, *hammer.Subscription) error); ok {
		r0 = rf(tx, subscription)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
