// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// TopicRepository is an autogenerated mock type for the TopicRepository type
type TopicRepository struct {
	mock.Mock
}

// Find provides a mock function with given fields: id
func (_m *TopicRepository) Find(id string) (hammer.Topic, error) {
	ret := _m.Called(id)

	var r0 hammer.Topic
	if rf, ok := ret.Get(0).(func(string) hammer.Topic); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(hammer.Topic)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: limit, offset
func (_m *TopicRepository) FindAll(limit int, offset int) ([]hammer.Topic, error) {
	ret := _m.Called(limit, offset)

	var r0 []hammer.Topic
	if rf, ok := ret.Get(0).(func(int, int) []hammer.Topic); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hammer.Topic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: tx, topic
func (_m *TopicRepository) Store(tx hammer.TxRepository, topic *hammer.Topic) error {
	ret := _m.Called(tx, topic)

	var r0 error
	if rf, ok := ret.Get(0).(func(hammer.TxRepository, *hammer.Topic) error); ok {
		r0 = rf(tx, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
