// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	hammer "github.com/allisson/hammer"
	mock "github.com/stretchr/testify/mock"
)

// TxFactoryRepository is an autogenerated mock type for the TxFactoryRepository type
type TxFactoryRepository struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *TxFactoryRepository) New() (hammer.TxRepository, error) {
	ret := _m.Called()

	var r0 hammer.TxRepository
	if rf, ok := ret.Get(0).(func() hammer.TxRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(hammer.TxRepository)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
