// Code generated by mockery vv2.7.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WorkerService is an autogenerated mock type for the WorkerService type
type WorkerService struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx
func (_m *WorkerService) Run(ctx context.Context) {
	_m.Called(ctx)
}

// Stop provides a mock function with given fields: ctx
func (_m *WorkerService) Stop(ctx context.Context) {
	_m.Called(ctx)
}
